### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by marco-vaz** [iwat/talib-cdl-go#1]
Hello,

Cloned and tried make with errors.

> ta_ACCBANDS.c:273:17: error: ‘es’ undeclared (first use in this function)
      tempReal = es.High(i)+es.Low(i);
                 ^
ta_ACCBANDS.c:273:17: note: each undeclared identifier is reported only once for each function it appears in
ta_ACCBANDS.c: In function ‘TA_S_ACCBANDS’:
ta_ACCBANDS.c:459:33: error: ‘es’ undeclared (first use in this function)
 /* Generated */      tempReal = es.High(i)+es.Low(i);
                                 ^
Makefile:773: recipe for target 'ta_ACCBANDS.lo' failed
make[2]: *** [ta_ACCBANDS.lo] Error 1
make[2]: Leaving directory '/opt/talib-cdl-go/c/src/ta_func'
Makefile:460: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/talib-cdl-go/c/src'
Makefile:465: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Could you please provide further usage information ?
Cheers

**Comment by iwat** [comment]
Hi Marco,

The C folder is a original C code for the functions that are not yet ported to Go. I keep it here so that I have a list of unfinished tasks.

In order to use this library, it's far easier than you think.

```go
package main

import (
	"fmt"

	"github.com/iwat/talib-cdl-go"
)

func main() {
	s := talibcdl.SimpleSeries{
		Highs:  []float64{21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 215, 245, 235},
		Opens:  []float64{11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 110, 240, 230},
		Closes: []float64{20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 200, 220, 150},
		Lows:   []float64{10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 105, 215, 145},
	}
	m := talibcdl.TwoCrows(s)
	fmt.Println(m)
}
```

The above code will output `[0 0 0 0 0 0 0 0 0 0 0 0 -100]` which means that the matcher finds bear signal (-100 = bear, +100 = bull) at the last data point of the given series.

`talibcdl.SimpleSeries` is a simple `talibcdl.Series` implementation.
